version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/movies/src
      - ./pnpm-lock.yaml:/movies/pnpm-lock.yaml
      - ./package.json:/movies/package.json
